{% set name = "coffeescript" %}
{% set version = "2.2.3" %}
{% set sha256 = "7b337420304b4ec4521cf9e6afa560223cb4ac4951e1656e9354dab281da351e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jashkenas/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g coffeescript
  requires:
    - nodejs
   
about:
  home: https://github.com/jashkenas/coffeescript
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Unfancy JavaScript'
  description: |
    CoffeeScript is a little language that compiles into JavaScript. 
  doc_url: http://coffeescript.org/
  dev_url: https://github.com/jashkenas/coffeescript
  
extra:
  recipe-maintainers:
    - cshaley
    - sannykr
