{% set name = "coffeescript" %}
{% set version = "2.4.1" %}
{% set sha256 = "6a97c0c3eb4eb49aa58fe32702ee05fd0868672c14874c927abbfd1818551188" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jashkenas/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g coffeescript
  requires:
    - nodejs
   
about:
  home: https://github.com/jashkenas/coffeescript
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Unfancy JavaScript'
  description: |
    CoffeeScript is a little language that compiles into JavaScript. 
  doc_url: http://coffeescript.org/
  dev_url: https://github.com/jashkenas/coffeescript
  
extra:
  recipe-maintainers:
    - cshaley
    - sannykr
