travis:
  secure:
    BINSTAR_TOKEN: dlerHFjCXIeNGErDDpaAg+hLZNUgDj9Be1jNEXFzfXLDPAzkPlG/Xt06Fc88lSOhiKjitCQjJhMlLXcmRn71cEcX1qNhs1L5EsJZGr4beTNdM3qsgEkTZjxJ1Nksdtdc6PJlwv2HtprEC6HXphPAod6O/XtnFH3mldxUibrO8DXhHJKMH5HaoRsYMGkSDH6r/0GCd8sPz5nGU/Icw8dmD7I6O44+bBFF7DTCJ7AZlCE1pmmB4jTtpIHpLphDwHYrWfTiy2mAqJ06CCkSaNxiMALyD3ivhYdBRvD8q9G/QjBVWSlpEpBE9bYJ13CiZTNDve7D44SDfff4MW9qvpDGzN8sDWu/w7AMLWWJ6L2cnECvXW7j+2/aRgHzIv18GoJGdxEABvuMfAe3HMInqYn18CweYNrcD0ZLbtrz9AcI6OKvPunl/kSb+ZBEMXiipixVicX6F9EdIzLrk4yLFsV5Q0GprgW2SWdFZ/CD6I/b2JGHXIUgzL76jRC7OKugXeRtBFoEZZ6n4x70pZEH3stm3p6rFvMNhukTfB5gR8xkl6kpSeSEdl7dJS8PpcAj4WeEINbmgDdq808HmhBX5XbOWEQEi4Gwg5AM/Mh8JPAgtMTlbPZOwLrUMggDTBykeTXOXeikWkJfsaV+QOsWoCw7sQuYsK+NiM0wa9g6mqulpc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
