travis:
  secure:
    BINSTAR_TOKEN: X8DX+hZVx5P/7qer7XIpja1GnLwWFysdVg71/bEheK+q+Y+bVnhDMeYBjutak4A/EcHPahZmq6BHMIMAfrlAxn6t5TU+rDWw2BwKUZQOaZVxenA8JWYbnGh6Qb32PSm7itU0gRsHdbJo0S7U+OZBrnJrsqAckOQ7xe9qD/yJHfxOB1DilI2m+0T4vmdPuUrm23ODVcemAm1ztxK6T7RQ/FzupfnaoAQ8PKqgV8VtJWVMIfd6RAkwpiTLNohsjPqd9/RCIHKwCsuNJSDiSyPFskh74Tb5HMd29BQvflTj1ePlgdRHgBlE79ac0O8nwaGgnJKygwaCSDaC4CdCPhacvBkHykp0tWcEnbTjGYARwxw6VENP+Jgzg8540/RVqxMiHI6A+7i9Yh/VTWIJzMcOaBmK2d96ZVfbhog078DEi1ZCNHpaa1mB+fm1ERxlNT0lAJz/3g2e1aI/g8USesKFHguu5Cqe7mKJEIyzsoc8QSqMppV3zGfROOhS+UwkbeUGJFJO8eO2TGwCOmZs6uFk36ZInAg62Muvqzg8M3urkk1SGqAxonFDMeHeGpYCoPOcoGCUI/mQxlE/3slMUeM8j/4H+Ff0iKjW31HJfwbR2I4PsWJrL9wToj40wmdqOICy43V1k9mIP+uNIzERbtQgMRjb26AsH9qvCkhtBP6Joio=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
