travis:
  secure:
    BINSTAR_TOKEN: fLiuxy3wL3ic/01sD6KfpbOXRJvM35kRbrGRzveQ+Kv4JOtBZI6qfAk5jrqcveny18GGYjHtFf0nJkiO2/DvUYQhbbRJZmkmbrkx2Z/1qpUvY+sk5CjZNkkLWla208UQADMKYDeoMxGEU8I6colkuIBMHZWzoB+b/zInMyufWlUnABLvjXHLvG+5d7NBnleRFmSynSqz0eB31/49DQ5QzVjMDBDvy/8gZry+rw6jI5c1+IDnU3QQhxD8gJX5cvq/LyW56IAFd5PLsNdoYdRkrcb8rcSO0U/emB9YThaAvY478hDpij584A78+ILoebtM+F3hETlJcaKwQtFhG1/Sa5+cHtv4F4M47b4zs8DJK9wm5b73yg+AUbeyypTblNXyHcMsbQiXyGQYWFY5bxFAW1qVPlefsRCy4q2sMbi2JOIiSnH140pspMUug/Ljhs0uaTuyHXYm+WNR/f094ZTY0B4icRHxNYKCULz5Kfi5IEricYGIFBDB0y8GwGwV85Lg7nt6bgt3PuAzNk9UZo6HNxUk5mNyy14N9y2SMvj3M+8oBa08xV+k73JuCJPIawMwaIg3vdkZx4pPCtM6QOyidaolO5+QmGaRhOwrmYKXbm6egrvdOBGCcNXAyYaYobC2Uh3CW9Pn6ZuHhsXriI1fSaBaBU+dD374PQY+dNRIcDs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
