travis:
  secure:
    BINSTAR_TOKEN: gEhABLO8gnyHjzDbS495Et3X4ukWcTQX+Q+XrKUDWfwASu5ynHbYFAWY1rAx6AGvE0QN3uEFfzXJs8zH9uGGYaCFUpxf/O7NwM4WLOc0rz7gg4IZfVnRgUK+Jq5EF3k1SWVT3DRMhXKDXBHLjqiLBcEa7Ruk2njj7RWp8ogUJaIO2jkyVeTHvBiDvOxPRaV8FocqSYDO5pFYxA9VrCHJ3T6CYACCZZCRYOFzJq20PygWznCNhOh5JH/kFRKaPMjJEMs6natr4ASmOMisUgSg4aiF63tWtEPAX06wwJ4r7bxKdY4sdMGLRPg1NjUHuBO9wcxQ25aDs/9Rlip5q1cjZMr5YIsdJdvT79c0dduBf2Cj/VPYFwOyl0WgtyJyCRZODKljFh3OGbR6LwQWX3MDW6gL9D8efQMv8J/LJCx/tzzLTII0MZE/X2ymaCbQ10bd3wnFt1pOkEF4G+vpSzeemiJSkPLHVL4WbSfT3D92giyq/+1VPt1T9DggrawmrxV9fHwiwQ2YtXMHvDHTlJ3Zs2GsTqSbPneVHMZ45njhVrZ8vW3bkmJ0wVEJ0s1qsgRpotYTMfriYgCEYiuVCtliYcwWT/32I5R4VNuLDrf6zk83ZXHke1xeueKKbvtk12cx9IbEMLqQbDwKTFaQiJx5V9fglTPAUlg6T+We+usskek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
