travis:
  secure:
    BINSTAR_TOKEN: Wo21wu6PwcjUmhFrbQPLjFqZCOTAAvQfZIv1sCtInf7YFT8AvKqFSNL5aSpaIb2Y02OO/sbG/dMy7os7ZbaKjX/XTM0nC2tcIS0LycHLzX6LyDQRdIN/trywLOoJSrw9frsVfYiN5j3XKPgkmaIVsL0Pn3JUm5XyBuolXiV6npIUCCN/GU5m5rpe3m6BzBBPtOL/Be1phNBm9uzXisgs+mpIFthVoXubheXiOD45fQFRilo4sI9ZV4fQT92MzkcvmWHyWkOlEPp+Fvs71KXwlm6hnUea/6fiId830O1yUicLFSylilMI3DEYT6jRHluqa5d6IH8cQqHIS2OYEve4JhgStIVYw4F0FNXoD0nrjSctnASS4rVPSrwxUIvMKnF2jxbdDqX66iQTA9iO6mCMhdKCbPAzNj+5Ob9IGg5y7EQ+pVbrnr+aee1UQOmycPUsbE7DmxnJwv9Qb40zMYY3EwSJLm4qHfFGiltr048Qhw/LEagBw4ALKNu/tghA0Z/xGoM2A7UXm0H6Mw5WrjtObxpwt/6JbW8/Yboxk1XKqzHpkm/VViF4U+lygnv3IpvEiHGdHHJZpEPYrKtRoPPAsgm4K1EHtgBHRqYr3x/4uSG2RlMcHLpR6P8YAOrjkDVxg7F/uFj4/+IHSAn1VIFm5zinp3siH6V7FhSaqkcwZz4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
