travis:
  secure:
    BINSTAR_TOKEN: r95ZuEDhnP4KaD0+y/E6EAWxXszKoK6XxZ9xcI9bWdu0V0zMOU76p3aq3pjKz4eYbCj+kqsP7lvJeYVubOsxM7YNeekjhEuolTerhOmI+B0TZQ3Q1VPaw9DEze0314PSeJ9x/v7KddHh07CsZSesOZZYGGH7WwCOKhPGOniBTeT6LPnpwihVdBclH7Cpq1nZd4u8MCeB+GQ+Qa/DVgfLvdT2ViXTq+QfSXvJnF4nefTIAqo1/bb3pVCX9yDdiJ6WuFDrrbmVAHIBCtDJtSdm6N7/qYnRL1ShQdZhoCiV6o1hnKehzEplmmQRRwvoJILlJxUzoun14fCsmKx7Ru24koILnp9XGqxA2n+BsVdn22JUDnZBvALLMLJhFtUOuIWp/c+hFc/FsZ1hEY3o3WCNgv4U2y8nJyrg6qj3Z4xbPmsfPTtmO47G2ISU+P7MP8hMBadAkmOnJ7FScvO7YFpF7n8I8jAS5h8qtTThkJ7qejGiCEFF4YyadG3ScInJnevaHBlUU5J/wpLYk+pDqVfs3euTZajgRenVrL+f48tJlpweHJ5USDspmwvT8xtAL8loaL6K6mF9qfFgQl9jw0gE9kEmjK9EpzAhzDZBOvHi/mwhvcL0jQ24Xy2z/ETDV9LMUXs/8RjTKKo8XAW9dbnE7wn9d35mgwANNzispQcam4A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
